version: '3'

services:
  postgres-compose:
    image: postgres:15.1-alpine
    container_name: postgres-compose
    ports:
      - "5432:5432"
    volumes:
      - pgDB:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    image: redis:alpine
    container_name: redis-compose
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data
volumes:
  pgDB:
  redisDB: